### ISSUE TITLE
PointerEvents set to none when modal: true

### ISSUE THREAD

**Issue by lcpriest** [shipshapecode/ember-shepherd#149]
Is `modal: true` supposed to be a walkthrough/non-clickable mode? 

Relevant code here:
https://github.com/shipshapecode/ember-shepherd/blob/c01523580a32bca00fed316ad35713f024b9047b/addon/services/tour.js#L367

```
if (this.get('modal')) {
  currentElement.style.pointerEvents = 'none';

  if (step.options.copyStyles) {
    this.createHighlightOverlay(step);
  } else {
    $('.shepherd-modal').removeClass('shepherd-modal');
    $(currentElement).addClass('shepherd-modal');
  }
}
```

**Comment by rwwagner90** [comment]
Hi @lcpriest yes, it should. I'm confused, did you want users to be able to click element underneath the greyed out overlay?

**Comment by lcpriest** [comment]
I was hoping to pop the relevant elements above the overlay using z-index, i.e. certain form fields that are relevant

**Comment by rwwagner90** [comment]
This should be possible potentially. I'm open to a PR to support it, if it's not already possible 😄

**Comment by rwwagner90** [comment]
The elements should be popped out, if done correctly, and if not, you can try copyStyles. Going to close this, but feel free to make a new issue if you want to pursue this further.
