### ISSUE TITLE
Route Transition

### ISSUE THREAD

**Issue by chvonrohr** [shipshapecode/ember-shepherd#165]
Is there already a way span a tour over multiple routes?
I tried with the ```beforeShowPromise``` function, which fires the promise too early before html classes are available...

```js
this.get('tour').set('steps', [
  {
    id: 'intro',
    options: {
      attachTo: '.first-element bottom',
      beforeShowPromise: function() {
         return new Promise(function(resolve) {
             router.transitionTo('myurl').finally(() => {
                 resolve();
             });
        });
      },
     // ...
}]);
```
Any recommendations?

thx

**Comment by rwwagner90** [comment]
Hi @chvonrohr I think people have submitted issues on this before, but I can't seem to find them. I think it is not currently supported. You would probably do one set of steps for one route, then stop the tour on transition and start it again with new steps. If you have an idea of how to make this easier, I'd love a PR to make it more seamless 😄

**Comment by chvonrohr** [comment]
😄  ok, thanks for your reply...
I would prefer to not split tours, as I load them async and they will span over many pages.

By now, I add some milliseconds before I resolve the Promise, but this is rather hacky. 
I'll investigate a little more and submit a PR if possible.

**Comment by rwwagner90** [comment]
@chvonrohr rather than adding time, you could try wrapping in `Ember.run.scheduleOnce('afterRender', this, function(){})` to make sure it runs after render.

**Comment by chvonrohr** [comment]
I don't know why it didn't work the first time I tried, but using ```afterRender``` works now... :-)
Using the the new router service (or router-polyfill before 2.15), this looks as following:

```javascript
this.get('tour').set('steps', [
  {
    id: 'intro',
    options: {
      attachTo: '.first-element bottom',
      beforeShowPromise: function() {
         return new Promise(function(resolve) {
             router.transitionTo('myurl').finally(() => {
                  Ember.run.scheduleOnce('afterRender', this, function() {
                      resolve();
                  });
             });
        });
      },
     // ...
}]);
```

thx for your reply and your work. Issue can be closed...

**Comment by rwwagner90** [comment]
Glad it works @chvonrohr! Would you be interested in writing something up about this for the README?

**Comment by chvonrohr** [comment]
@rwwagner90 sorry, did not see your reply earlier. 
But I saw, that you already added it to the Readme. thx for the update and your great addon!

With that method, there is **only one drawback** I experienced. An error appears, if a redirect is made on a route. Means, if you ```transitionTo('myurl')```and my url has a further redirect in the route, ```didRender``` fires too early. Workaround for me is to point directly to this route.

**Comment by tchan** [comment]
Hey @chvonrohr do you have an example source code I can take a look at? I've followed your example and keep getting router is undefined.

**Comment by rwwagner90** [comment]
@tchan you can inject the router service into anywhere you need it. `router` is not a global thing.

**Comment by chvonrohr** [comment]
Hey @tchan 

As rwwagner90 wrote, you have to inject the router service first.
For ember < 2.15, you need this polyfill: https://github.com/rwjblue/ember-router-service-polyfill 
for ember 2.15 and above the router service comes with the core.

```javascript
import { inject as service } from '@ember/service';

export default Controller.extend({
  router: service(),
  
  startTour() {
    // .. code from above
  }
});
```
