### ISSUE TITLE
Integration tests failing when injecting the tour service.

### ISSUE THREAD

**Issue by timjcook** [shipshapecode/ember-shepherd#184]
Hi there 👋

I've noticed that after calling the `tour` service in one of my components, that component's integration test would start failing with the following error `Attempting to inject an unknown injection: 'service:window'`.

I tracked it down to the `ember-window-mock` library that is a dependency of `ember-shepherd`, specifically here https://github.com/kaliber5/ember-window-mock#integrationunit-tests

I fixed my issues by following the steps outlined above ☝️  but it required a bit of hunting around.

Not sure if you can think of a fix to avoid this being an issue or perhaps just a documentation update to let people know that could be an issue.

Apart from that, enjoying the library, thanks ✌️

**Comment by rwwagner90** [comment]
Hi @timjcook! Thanks for reporting! That is, unfortunately, one of the current limitations to ember-window-mock. If you can think of a way to get around this or if you just wanted to document it, I would gladly accept a PR 😃

**Comment by timjcook** [comment]
Great, I'll have a think about it and get a PR with at least a doco addition soon.

**Comment by rwwagner90** [comment]
Sounds great. Please let me know if you need any help from me. Thanks!

**Comment by rwwagner90** [comment]
I just released version 3.1.0 of ember-shepherd and removed the dependency on ember-window-mock, so that should resolve this issue.

**Comment by timjcook** [comment]
legend! thanks heaps @rwwagner90. sorry I didn't get a PR together myself. been away for a few weeks 👌

**Comment by rwwagner90** [comment]
No worries. Enjoy!
