### ISSUE TITLE
Default highlighting/arrow ui

### ISSUE THREAD

**Issue by knownasilya** [shipshapecode/ember-shepherd#197]
Would love a non trivial implementation of highlight that basically positions a div over the target element so that it doesn't affect ui. On a related note, a default arrow that points to the element would really help as well. Either one of these or both of them would really improve the user experience.

**Comment by rwwagner90** [comment]
@knownasilya can you say more on this?

**Comment by billybonks** [comment]
This sounds like a tour implementation that i saw for react where they have a div that is sized over the item you want to highlight and builds the back drop using a box-shadow that covers the whole page. that div is absolutely positioned around the app.

**Comment by rwwagner90** [comment]
I'd be happy to work with someone on an implementation for this. Highlighting mostly works, but does have some issues, which is why I provided the copyStyles stuff to duplicate all the styles of the element and pop it out over the overlay.

**Comment by knownasilya** [comment]
So `modal` + `copyStyles` is basically what I wanted, but it wasn't obvious that's how it should be setup.

**Comment by rwwagner90** [comment]
@knownasilya it may be more performant to do it the way you were thinking, instead of the copyStyles method, if you had an implementation in mind.
