### ISSUE TITLE
Allow user to decide where to place the `shepherdOverlay` element

### ISSUE THREAD

**Issue by jbandura** [shipshapecode/ember-shepherd#206]
## Current behavior
The element gets appended to `body`. In my case, it's a bit complicated since I have to place it in a different element to make the highlighting work properly.

## Proposed behavior
The user can pass in an optional config option `modalContainer` (defaults to `body`) which influences where the modal element will be placed. Usage:

```js
// tour setup goes here
tour.setProperties({
  modal: true, 
  modalContainer: '.some-modal-container'
});
```

Let me know what you think :) Happy to create a PR in case the proposal is accepted.

**Comment by rwwagner90** [comment]
This seems fine to me! I see no reason why we couldn't default to `body` with an option to override.

**Comment by jbandura** [comment]
Glad to hear that, created a PR :)
