### ISSUE TITLE
Tether is end-of-life

### ISSUE THREAD

**Issue by davewasmer** [shipshapecode/ember-shepherd#214]
It might be worth mentioning in the readme that Tether.js, the library that Shepherd uses for positioning popups, is end-of-life. Plus, Shepherd's future seems tenuous at best given Hubspot's apparent abandonment of open source maintenance.

**Comment by davewasmer** [comment]
Certainly, and I don't mean to knock any of the efforts of the ember-shepherd folks - happy to see it so active.

However, I think it could be worthwhile to at least include a note in the readme. Not explicitly deprecating ember-shepherd, but just calling out that the underlying libraries are either EOL or uncertain in their future.

I'm building out a tour feature for a client project and got pretty far down the road with ember-shepherd, only to discover that Tether is EOL. Client doesn't want to build on EOL'd tech (understandably), so now I've got to start over. Would have been good to know from the start.

**Comment by rwwagner90** [comment]
@davewasmer I would argue that it's not really EOL though. It's stable and works great, and we've bolted on extra functionality here at ember-shepherd as well. Ember addons give us the opportunity to consume other JS libs and continue to support and improve upon them in our own way. ember-tether is also actively maintained https://github.com/yapplabs/ember-tether. I don't think it's fair to just abandon a bunch of really solid addons because HubSpot happens to not maintain some of the underlying libraries anymore. We could easily fork them, if there are any huge bugs or anything, but they mostly work really great.

**Comment by davewasmer** [comment]
> I would argue that it's not really EOL though. It's stable and works great

The Tether.js readme explicitly states that it is no longer maintained by Hubspot, and they recommend switching to Popper.js. The issue tracker has over 80 open issues, and after a cursory glance I'd estimate about half have no response whatsoever.

> ember-tether is also actively maintained yapplabs/ember-tether

Which still depends on Tether.js though.

> I don't think it's fair to just abandon a bunch of really solid addons because HubSpot happens to not maintain some of the underlying libraries anymore.

I think maybe I'm not being clear with my ask here - I apologize. I am definitely **not** recommending ember-shepherd be deprecated or abandoned in any way. I just thought it might be a good idea to mention in the readme that the underlying libraries are no longer maintained. If you have plans to fork and maintain them if and when that is needed, that would be a great note to include as well!

------

To reiterate - I'm super impressed by the work you and the other maintainers have done here. It's an awesome library, and I'm thankful for it's existence.

I just think it would be helpful to put a note in the readme describing the situation. I have a client who doesn't want to build on EOL'd tech, which is not entirely unreasonable, and I ended up burning a day and a half integrating ember-shepherd only to realize that I'll have to find something else. Including a note that could save others that kind of time (or more) in the future seems like a reasonable request (and I'm happy to PR it if you'd like).

If you still disagree, I'm guessing I won't be able to convince you otherwise; feel free to close this issue in that case.

Thanks again for all your hard work here (and elsewhere around Ember-land)!

**Comment by rwwagner90** [comment]
I totally understand what you are saying @davewasmer, but I think my argument here is I disagree with your client arbitrarily not wanting to use ember-shepherd, when it is currently the best rated and most solid (to my knowledge) addon to use for this. I don't disagree with your desire for a warning, I just want to help change your mind to see what we can do to get you using the addon 😃 .

**Comment by rwwagner90** [comment]
@davewasmer I was granted write access to the Shepherd repo, and I am actively talking with the folks at HubSpot about continuing Shepherd. It may be refactored to use popper. ember-shepherd and Shepherd will not be end of life, just FYI.

**Comment by davewasmer** [comment]
Awesome news, glad to hear :+1:
