### ISSUE TITLE
Jittery behavior with disableScroll in Safari mobile

### ISSUE THREAD

**Issue by alexmiddeleer** [shipshapecode/ember-shepherd#215]
Thanks for the great addon, first of all. This is not a major issue, but disableScroll does not seem to work smoothly in Safari mobile. In iOS chrome I see a fairly smooth "snap-back", but in Safari it jitters back and forth rapidly, creating a flicker effect which is a bit jarring to the user.

**Comment by alexmiddeleer** [comment]
I wouldn't expect it to - it seems to be the "snap-back" which is jittery. I can confirm, but I don't know what would stutter if disableScroll was off.

**Comment by rwwagner90** [comment]
I'm not sure what you mean by "snap-back". This addon scrolls to the next step when you click next/previous etc. I'm curious if the issue you are seeing goes away with `disableScroll` turned off or not.

**Comment by alexmiddeleer** [comment]
Sorry for the bad description... "snap-back" is how I was trying to describe what Chrome does when you have disableScroll on. It allows you to scroll about 100px then "resets" your scroll position, the animation has an elastic feel to it (as opposed to Safari mobile, which seems to be trying the same thing, but is jittery). With disableScroll turned off, you can scroll normally.

**Comment by rwwagner90** [comment]
Ohhhh, that sounds like a browser bug of some kind then. Disable scroll 100% disables scrolling. You cannot scroll at all. The snap-back thing is how the browser handles you scrolling, but ultimately does not let you scroll.

**Comment by alexmiddeleer** [comment]
Yup, we want to 100% disable scrolling, and the Chrome behavior is fine. I agree that it's likely a browser bug but wasn't sure how the internals of shepherd turn off scroll. Browser quirks.... 😢

**Comment by rwwagner90** [comment]
We use https://www.npmjs.com/package/disable-scroll but I think the issue would persist, regardless of how you disable scroll. The snap-back is built into Chrome. If you scroll past the top or bottom of a site it snaps back, the same with if scrolling is disabled. It's possible there is a way to disable that behavior as well. If you have any suggestions, I would be happy to try them out.

**Comment by alexmiddeleer** [comment]
Sure, I will try to do an investigation and if anything useful turns up, I will report back.

**Comment by rwwagner90** [comment]
Closing as a bug in browsers.
