### ISSUE TITLE
Add option for showing a step after render

### ISSUE THREAD

**Issue by BrianSipple** [shipshapecode/ember-shepherd#236]
Right now, if a user wants a step to show after render, they have to set the `beforeShowPromise` option and then manually construct an `afterRender` RunLoop operation:

```js
      beforeShowPromise() {
        return new Promise(function (resolve) {
          Ember.run.scheduleOnce('afterRender', this, function() {
            resolve();
          });
        });
      },
```

I feel like this is such a common use case, that we should be able to offer a Boolean step option such as `showAfterRender`, and, if it's `true`, handle the above functionality ourselves behind the scenes.

**Comment by rwwagner90** [comment]
@BrianSipple I would be okay with this, I think. Could we just build this in as the default behavior for ember-shepherd somehow, perhaps just wrap the show function in the run loop, rather than using `beforeShowPromise`?

**Comment by chuckcarpenter** [comment]
```javascript
function _waitForTargetElement(elementSelector) {
    return new Promise(res => {
      // Create an observer instance linked to the callback function
      const observer = new MutationObserver((mut, self) => {
        const targetEl = document.querySelector(elementSelector);

        if (targetEl) {
          // give the nav a moment to open
          later(() => {
            // stop observing
            self.disconnect();
            return res(targetEl);
          }, 200);
        }
      });

      // Start observing the target node for configured mutations
      observer.observe(document, {
        attributes: true,
        childList: true,
        subtree: true
      });
    });
  }
```

**Comment by chuckcarpenter** [comment]
otherwise, the only concern I'm not clear on is with this 'afterRender' and how the advanceOn element triggers it? Is that assuming it will be the next transition in the runloop?

**Comment by BrianSipple** [comment]
@chuckcarpenter I'm not sure I'm following where `advanceOn` would come in to play here. Ideally, the tour wouldn't be listening for events until `beforeShowPromise` resolves -- which would be after `afterRender` resolves.

Regarding the example you posted above, I think a better approach, instead of passing that to beforeShowPromise, would be to inject the tour service into whatever component you're waiting on here, and then call tour.next()

**Comment by BrianSipple** [comment]
Playing around with this a bit, it's tough for `ember-shepherd` to use the run-loop unless it overwrites `beforeShowPromise` -- because `beforeShowPromise` itself is handled in `shepherd`. 

@rwwagner90 @chuckcarpenter What do you think about offering a set of addon helpers that handled common `beforeShowPromise` patterns? Something like this:

```js
import { showAfterRender } from 'ember-shepherd/utils/before-show-promises`;

const steps = [
  {
    id: 'Step 1',
    options: {
      beforeShowPromise: showAfterRender,
      ...
      },
      ...
  },
];
```

**Comment by rwwagner90** [comment]
@BrianSipple `beforeShowPromise` is intended to run anything and everything you want it to. It's just any function, that returns a promise and resolves the promise when you are ready to call `show`. With that in mind, I think your `showAfterRender` seems okay.

However, why can't we just wrap the `ember-shepherd` `show` method in the runloop? Should work the same and handle these things automatically, without the need for `beforeShowPromise` right?
