### ISSUE TITLE
Remove usage of `.shepherd-transparent-text` class

### ISSUE THREAD

**Issue by BrianSipple** [shipshapecode/ember-shepherd#238]
The `shepherd-transparent-text` CSS class is used pretty liberally throughout the test dummy app, and it's even used as a default class for the "error" step we add in the `tour` service. 

However, I don't think this class is actually a part of the styles for `shepherd`, and we don't have any style rules for it here. It seems to be limited to [`shepherd`'s test dummy app styling](https://github.com/shipshapecode/shepherd/search?q=shepherd-transparent-text&unscoped_q=shepherd-transparent-text). 

If that's the case, I think we should get rid of it here to eliminate some confusion.

**Comment by rwwagner90** [comment]
@BrianSipple are you saying just remove unused classes from demos? The demos use some custom classes, to show that you can pass classes in and such.

**Comment by BrianSipple** [comment]
I'm not opposed to having dummy class names when we're demoing such usage. That said...

- I might make it a bit more clear that that's what they are. (Something like `my-custom-class-name`). 
- I think there are several cases where the usage makes things less clean -- especially [the case where `shepherd-transparent-text` made it in to the addon code](https://github.com/shipshapecode/ember-shepherd/blob/5539757d87bf781d2e93ee1ed09c6eae3db2d9de/addon/services/tour.js#L328).
