### ISSUE TITLE
Add helper for hiding a current step.

### ISSUE THREAD

**Issue by BrianSipple** [shipshapecode/ember-shepherd#249]
The `tour` service should have a basic `hide` function that performs what, currently, needs to be done with `tourService.tourObject.getCurrentStep().hide();`

**Comment by BrianSipple** [comment]
Update: We should be able to implement/document this after merging https://github.com/shipshapecode/shepherd/pull/265

**Comment by rwwagner90** [comment]
@BrianSipple we should be good to implement this now right?
