### ISSUE TITLE
Ignore button type

### ISSUE THREAD

**Issue by knownasilya** [shipshapecode/ember-shepherd#276]
One use case I found that the current button types don't handle is if you want to ignore the tour all-together, even when you come back later so it doesn't bug you every time.

Basically like a 'next' works on the last step, but able to put it on the first step.

**Comment by rwwagner90** [comment]
@knownasilya wouldn't this be better suited to a custom button that calls `cancel` or `complete` on the tour?

**Comment by knownasilya** [comment]
Yeah, I wasn't handling the events due to API changes that I didn't realize happened.
