### ISSUE TITLE
set steps error

### ISSUE THREAD

**Issue by yaxinr** [shipshapecode/ember-shepherd#288]
https://shipshapecode.github.io/ember-shepherd/
`tour.set('steps', steps);
`
do not work in ember 3.7 ember-shepherd: 4.5.3
```
Uncaught TypeError: Cannot read property 'start' of undefined
    at Class.start (tour.js:84)
    at Class.startTour (tour.js:21)


    start() {
      Ember.set(this, 'isActive', true);
      Ember.get(this, 'tourObject').start();
    },

```
this work
`tour.addSteps(steps);
`
because
```
    addSteps(steps) {
      this._initialize();

      const tour = Ember.get(this, 'tourObject'); // Return nothing if there are no steps

```

**Comment by rwwagner90** [comment]
@yaxinr `addSteps` is the currently documented and supported way of adding steps. We removed the `observer`, so setting `steps` manually will not do anything anyway.

**Comment by yaxinr** [comment]
change main page maybe https://shipshapecode.github.io/ember-shepherd/

**Comment by rwwagner90** [comment]
Ah, yes, need to change that. The README is the most up to date docs at this time.
