### ISSUE TITLE
Empty Changelog

### ISSUE THREAD

**Issue by Turbo87** [shipshapecode/ember-shepherd#294]
The [changelog](https://github.com/shipshapecode/ember-shepherd/blob/v4.6.0/CHANGELOG.md) for the last few releases mentions the releases but is otherwise empty. What were the changes in those last releases and why are they not mentioned in the changelog?

**Comment by rwwagner90** [comment]
Most of the changes were bumping Shepherd versions. I use github_changelog_generator and I think it does not list changes from commits that were not merged from PRs. It does have a link to the full changelog, showing the commits between the versions, if that is helpful.
