### ISSUE TITLE
Tour does not close on Route Transitions

### ISSUE THREAD

**Issue by SilvaMtz** [shipshapecode/ember-shepherd#314]
Whether I type the URL directly or move through the app, the tour does not close. I have tried using `willTransition`, `didTransition`, `deactivate`, and many other Route Methods, something like this:
`willTransition() {
     this.get('tour').cancel();
`
I have multiple tours on my app. When I move from one route to another with the tour open,  it does not close and stacks with the other tour. And the previous tour cannot be close even manually until the page is refreshed.

**Comment by rwwagner90** [comment]
Hello @SilvaMtz, can you please provide a reproduction of this or at least confirm your versions of Shepherd and ember-shepherd etc?

**Comment by SilvaMtz** [comment]
Upon changing routes, the begin stacking on top of the other. Unable to close the last one.

Shepherd v2.8.0
Ember-Sehpherd v4.9.0

<img width="1280" alt="Route 1" src="https://user-images.githubusercontent.com/17131846/59069230-259ed800-887c-11e9-95fe-1e640a0bb235.png">
<img width="1280" alt="Route 2" src="https://user-images.githubusercontent.com/17131846/59069231-259ed800-887c-11e9-96b6-aa4036489150.png">

**Comment by rwwagner90** [comment]
@SilvaMtz so two things here:

1. Would using just one tour and replacing the steps not be okay?
2. What have you tried to cancel the tour before switching routes? If you could provide a reproduction, I could try to help you find a workaround.

**Comment by st-h** [comment]
@SilvaMtz I noticed that this is probably not desired behaviour as well, as I am using a separate tour for each route in my app. To work around it, I just cancel the current tour on the `willTransition` hook.

```
actions: {
    willTransition: function() {
      if (this.tour.isActive) {
        this.tour.cancel();
      }
    }
  }
```

**Comment by rwwagner90** [comment]
@SilvaMtz @st-h when I originally wrote this library, I did not intend for multiple tours. I always reused the same tour and changed the steps out. I also know there are people who want the tour to stay active across route transitions, so there are use cases for both cancelling and not.

That being said, we could probably make this configurable. We could build something in that utilizes the router service or router directly, whichever is easier, and check `if(this.tour.isActive && this.tour.cancelOnTransition)` and manually cancel the tour. Thoughts?

**Comment by st-h** [comment]
@rwwagner90 I personally think it is fine that the app controls when the tour will be hidden - as it currently is. But, as you mentioned, one could always add configurable convenience methods to handle something like that - but well, it is quite easy to add that behaviour in the actual app in case it is desired.

**Comment by rwwagner90** [comment]
@st-h I agree, but I do want to make everything as easy as possible.
