### ISSUE TITLE
Clicking cancelIcon doesn't trigger "cancel" event.

### ISSUE THREAD

**Issue by BitBrit** [shipshapecode/ember-shepherd#356]
I will explain my scenario for context.

In each tour step (in modal mode) I have attached the tooltip to an element and the whole element stays active and clickable. However, as part of the tour, I only want users to click on certain buttons within the active element. All other buttons I disable as part of the tour step. 

When the tour completes, or when the tour is cancelled (via the `cancelIcon`), I need to re-enable all the disabled elements. To do this a have a function which needs to be called on cancel or complete. This function is called when the "cancel" event is triggered. 

This problem is that a click on the `cancelIcon` button doesn't seem to trigger the "cancel" event.  

Two questions:
1. Should the "cancel" even be triggered on a `cancelIcon` click?
2. Am I following a recommended pattern for disabling and re-enabling elements?

**Comment by BitBrit** [comment]
@rwwagner90 My apologies for my lack of knowledge, but how does one distinguish be ember events and native events so that your question can be answered?

**Comment by rwwagner90** [comment]
@BitBrit a code sample should suffice. If you're using ember-shepherd, I assume you are not manually interacting with Shepherd, but using the addon, so you're likely not listening to the Shepherd events.

You would have to get a reference to the `tourObject` and add a listener.

```js
tourObject.on('cancel', () => {
// Do stuff on cancel here
})
```

Are you listening for the cancel event like that or how are you setting up your event listener?

**Comment by BitBrit** [comment]
@rwwagner90 I have created a gist: 

https://gist.github.com/BitBrit/6964cc008494f6f8e178cb79dc78585a

This gist if of my app's tour service which is inherited from `TourService` from ember-shepherd. Lines 41 - 51 have the two listeners for the "complete" and "cancel" events.  These are the methods that correctly fire on a "cancel" button type or tour completion but don't for the `cancelIcon`.  

Does this help show what I am trying to do?

**Comment by rwwagner90** [comment]
@BitBrit I do not see any event listeners in that gist. It just appears you have overridden `complete` and `cancel` with your own methods.

**Comment by BitBrit** [comment]
And what triggers the `complete` and `cancel` on the tour object?

Again, excuse me if I have missed something but I followed this to set my understanding:
https://guides.emberjs.com/release/components/handling-events/
I made the assumption that what is described here works for any ember object. You define a listener and it catches events bubbled up to it.  Is this not correct? 

Either way, the code works for the button and not for the `cancelIcon`. Any ideas?

**Comment by rwwagner90** [comment]
@BitBrit we're talking about different things here. You have extended the service and overridden the method. The method is not an event, it is a method called to complete or cancel the tour. `tourService.complete` is what you call to complete the tour, etc.

I believe you would want to use a listener on `cancel` instead :

```js
tourService.on('cancel', () => {
  // Do stuff on cancel inside this cancel listener
});
```

We're using Ember Evented, so it could be helpful to check out the docs there https://api.emberjs.com/ember/release/classes/Evented

**Comment by BitBrit** [comment]
Thanks! The events work better but, just for my edification, what is it that calls the `complete()` and `cancel()` methods when I use the "cancel" type button instead of the `cancelIcon`?

**Comment by rwwagner90** [comment]
We provide the button types to make things simpler for creating the common types of buttons people usually use. They bind to their corresponding methods here https://github.com/shipshapecode/ember-shepherd/blob/master/addon/utils/buttons.js#L31

`cancelIcon` cancels the tour, it does not call the Ember service's `cancel` method, so listening to the events is the best way to handle these things.
