### ISSUE TITLE
Acceptance Testing Tour causes second test to fail

### ISSUE THREAD

**Issue by BitBrit** [shipshapecode/ember-shepherd#360]
I am trying to test my ember-shepherd tour using an acceptance test. The first test I have is the "happy path" i.e. it tests that the tour works from start to finish if all expected things happen (user clicks on the correct buttons, API responds successfully etc.).  The second test is designed to verify that the tour ends if there is an API error during the tour.  I use the `waitFor()` ember test-helper function to make the test waits for the first tooltip in the tour to appear. 

Individually the tests pass but, when run together, whichever test runs second fails. The `waitFor()` times out waiting for the tour to start.

When running the tests in the browser I use `pauseTest()` to pause at the start of the test.  When I do this for the failing test I see that: 

1. the tour starts, 
2. the modal overlay is rendered (as I'm running the tour in modal mode)
3. but the initial tool tip is never displayed.

Has anyone seen tests on the ember-shepherd tour interfere with one another? Is there something I should be resetting between tests?

Thanks.

**Comment by rwwagner90** [comment]
@BitBrit are you doing anything differently than we do in our internal tests? https://github.com/shipshapecode/ember-shepherd/blob/master/tests/acceptance/ember-shepherd-test.js

**Comment by BitBrit** [comment]
Depending on how granular I go, yes.

Here are a few things I notice:
1. I don't start the tour in my test, I visit a route which starts the tour.
2. I don't call `tour.complete()` after each test. The idea here is that the test completes itself via successful completion of the tour, cancelling, or correct handling of errors.  
 _Side Note: Line 25 `await`s a promise but https://github.com/shipshapecode/ember-shepherd/blob/9058708218169cc3a27f5cfa63a1d304caa540cf/addon/services/tour.js#L291 does not seem to return promise. This is the same for Line 9 in the test when `tour.start()` is called._  
3. My test had a few more steps in it than yours. Not that that should matter as everything is torn down and reestablished for each test, right?

Other than that, our tests look similar. My tests and yours both visit a url (the same URL) and then run assertions on what happens.

**Comment by rwwagner90** [comment]
@BitBrit without seeing and being able to debug the tests, I am afraid I cannot be much help. I would recommend trying to do similar `await` and such as we do in our tests, and to ensure the tour is completed after each test. I suspect that the test is not done tearing down when you transition routes.

**Comment by BitBrit** [comment]
Ok thanks for the response. At least your response tells me that you haven't heard of this before and so there are no obvious fixes.

**Comment by rwwagner90** [comment]
@BitBrit the TL;DR here is you just have to make sure the tour is completed and totally torn down. I would do an extra `tour.complete` or `tour.cancel` etc in `afterEach` just to be totally sure.
