### ISSUE TITLE
Question: Attaching to elements in the corner

### ISSUE THREAD

**Issue by boydkr** [shipshapecode/ember-shepherd#41]
Is there any way to offset or alter the attaching behavior for elements that exist in the corner of the page?

The default behavior of centering on the selected side of the element doesn't work very well for elements in or near the corner, currently.

**Comment by rwwagner90** [comment]
Hi @boydkr you should be able to tweak `attachTo` to do what you want. Try using `left`. Does this accomplish what you are going for?

**Comment by boydkr** [comment]
If an element is to far into the corner of a page (i.e. top right corner), both `left` and `bottom` positioning result in the attached element losing it's "desired" position and formatting, because it can't fit on the page and be centered on the `attachTo` element.

I can try to put together an example screenshot if that would help.

**Comment by rwwagner90** [comment]
@boydkr `attachTo` is a built in option of the Shepherd library. I'd be inclined not to work around that, as we don't want to get into writing our own tour library, just extending theirs and wrapping it for Ember. Please check out the official Shepherd library http://github.hubspot.com/shepherd/ . I assume the same behavior happens using that and not just with our addon? If there is an issue with the addon, we'll be glad to fix it, but this may be an issue for the Shepherd team.

**Comment by rwwagner90** [comment]
@boydkr did you look at the actual Shepherd library to confirm this behavior?

**Comment by boydkr** [comment]
I'm sure you're correct, that the behavior in inherent in Shepherd itself.  I may try opening an issue there.

**Comment by rwwagner90** [comment]
@boydkr I don't think that there is. I think it makes the most sense to support this on the Shepherd level, but if you would like for Ember-Shepherd to support it, and the Shepherd team does not want to, we'd love to work with you on a PR for it :smile: .

**Comment by rwwagner90** [comment]
@boydkr let me know if you'd like to work with us on creating support for this. I'm going to close this, as it is a Shepherd issue, but we could potentially support it here.
