### ISSUE TITLE
Check for required elements on tour start?

### ISSUE THREAD

**Issue by craigsketchley** [shipshapecode/ember-shepherd#42]
Hey, I was thinking we should probably be checking for the required elements when the tour starts. I've found that, between setting the steps and starting the tour, elements might change on the page. I am setting the steps of my tour for a route in `setupController`, so is maybe there's a better place to do the tour configuration?

**Comment by rwwagner90** [comment]
@craigsketchley why not just set your steps after the elements you want are defined?

**Comment by craigsketchley** [comment]
Yeah, I definitely could. I'm just thinking it would be an improvement from a usability perspective. It feels like checking for the required elements on the page would be better associated with starting the tour than configuring the tour. Things are breaking at the moment if you set the required elements after setting the steps and I wouldn't know why without looking inside the library code - I think it'd be neater if this wasn't the case. The same goes for the requirement for [setting the defaults](https://github.com/shipshapecode/ember-shepherd#you-must-set-defaults-before-setting-steps) before setting the steps - it'd also be good to remove this requirement.

**Comment by rwwagner90** [comment]
I was trying to avoid doing all of that when you call start, but maybe it's not terrible to have it happen on start. I feel like I had reasons for it, but I can't remember them. I'm open to a PR, if you'd like to give it a shot.

**Comment by craigsketchley** [comment]
Cool. I'll have a crack at it.

**Comment by rwwagner90** [comment]
Maybe we should rewrite it to just set it all up in one config object and then set each respective thing. Let me take a look this weekend actually.

**Comment by rwwagner90** [comment]
@craigsketchley as a side note, I started an organization Ship Shape and I want to just build a bunch of Ember Addons for the community and add them to the organization's portfolio. You may have noticed I moved this addon into the organization already. Not sure how interested you are in the addons I have created already or if you have ideas for new ones as well, or if you even have much time to devote to open source dev, but would you be interested in being a part of it?

**Comment by rwwagner90** [comment]
@craigsketchley I ended up having a lot of other stuff to work on this weekend working towards getting the Ship Shape website up and running. I'll definitely take a look at moving all of this logic into the tour start this week though. I think we can get one central config and setup will be a lot smoother. Sorry for the delay!

**Comment by craigsketchley** [comment]
No, no worries. I was moving house so didn't have any time to look into either :smile: Yeah good plan. Let me know if there's anything I can help with.

**Comment by rwwagner90** [comment]
@craigsketchley I think the issue here is, if we move all the logic to when the tour starts, every time you stop and start the tour, it has to do all the setup again, versus having the initialization of a new tour only happen when you change the steps. What are your thoughts? I'm open to suggestions on how to implement this.

**Comment by craigsketchley** [comment]
My initial thoughts were to essentially extract [this required elements check](https://github.com/shipshapecode/ember-shepherd/blob/master/addon/services/tour.js#L304) from the `steps` observer into it's own observer on the `isActive` property. I'd also probably remove the `autoStart` from the `steps` observer too, feel like that should be called in an ember lifecycle hook. I've got the start of these changes in my own fork - [here's the diff](https://github.com/shipshapecode/ember-shepherd/compare/master...craigsketchley:requiredElements).

**Comment by rwwagner90** [comment]
@craigsketchley I think we have to completely remove the steps observer, and just do all of this stuff when `start` is called.

As for autoStart in a hook, what hooks are available inside an Ember service?

**Comment by craigsketchley** [comment]
Yeah, I think you might be right - rather than rely on observers where the order is less defined. As long as all the processing doesn't noticeably delay/lock the tour from starting.

I looked into service hooks and there doesn't seem to be any we can use. I'm thinking that maybe `autoStart` shouldn't be the responsibility of ember-shepherd? If an app is setting `autoStart: true`, then they may as well call `tour.start()`. Auto starting the tour on some condition sounds like logic for the app to handle.

**Comment by rwwagner90** [comment]
I agree with your thoughts on autoStart. We probably should just let the user start it whenever they need to.

**Comment by rwwagner90** [comment]
I've still been spending most of my time working on the new Ship Shape site and the ember-3d-nav. Feel free to think about this some more and let's try to nail down exactly what we want and then we can implement it.

**Comment by craigsketchley** [comment]
:+1: sounds good. I might have a hack around and get a rough PR up.

**Comment by rwwagner90** [comment]
A PR would be great :smile:. I can't really fully dive into this until I fix up the website.

**Comment by rwwagner90** [comment]
@craigsketchley any more thoughts or progress on the issue?

**Comment by rwwagner90** [comment]
@bekzod also feel free to give your input on this issue.

**Comment by rwwagner90** [comment]
@craigsketchley haven't heard from you in awhile. You still interested in working on this?

**Comment by craigsketchley** [comment]
Hey @rwwagner90, yeah sorry, a shepherd tour became low priority for the product I'm working on. I can probably get round to this at the weekend?

**Comment by rwwagner90** [comment]
@craigsketchley do you think you could work on this soon? I'd love to close it out. I have a ton of side work I am doing now, so I don't have time to implement this myself currently.

**Comment by rwwagner90** [comment]
@craigsketchley any updates?

**Comment by rwwagner90** [comment]
@craigsketchley I'm inclined to close this if there is no longer any interest in working on it. Let me know please.

**Comment by craigsketchley** [comment]
Hey @rwwagner90, really sorry I haven't gotten round to this. I'll submit the PR tonight.

**Comment by rwwagner90** [comment]
@craigsketchley no worries, we're all super busy. Just wanted to check if there was still interest

**Comment by rwwagner90** [comment]
@craigsketchley could you submit that PR please?

**Comment by craigsketchley** [comment]
Hey @rwwagner90. Sorry for being slack here, taken on way too much lately and we're not using this in our product anymore so became a little hard to justify working on it. I've had a play and it turns out to be a bigger task than anticipated. Not sure I'll get much free time until July (University exams 😞 ). I've pushed what I've got to the [`requirdElementsFix` branch](https://github.com/shipshapecode/ember-shepherd/tree/requiredElementsFix) and it's working well, but it still needs a bit of work (testing). Moving all the tour creation into `tour.start()` does make it difficult to unit test the service, so not completely happy with it.

**Comment by rwwagner90** [comment]
@craigsketchley no worries at all. Thanks, I'll check it out. Did you switch to a different tour library or did you remove the tour completely, in your product?

**Comment by craigsketchley** [comment]
Cheers. We're just not using a tour for now. We decided to reprioritise some features and it got bumped way down. We may revisit it in the future though.

**Comment by rwwagner90** [comment]
Gotcha, just glad you didn't find a better tour library out there 😛

**Comment by rwwagner90** [comment]
I'm going to close this for now. If anyone in the future has some big problems with this issue. Please leave a comment and we can look at implementing it.

**Comment by rwwagner90** [comment]
@evoactivity your elements would not be there until the page renders, so I don't think `beforeModel` or `afterModel` are what you want here. You want to wait until the page is rendered and then start the tour.
