### ISSUE TITLE
Tours are not testable

### ISSUE THREAD

**Issue by grapho** [shipshapecode/ember-shepherd#449]
I recently upgraded to the latest release. I was originally using v4.0.0-beta.10

I am unable to test tours in ember Acceptance tests. They render outside of the testing container and therefore no way to assert or click through the steps. It is especially egregious when the tours use scrolling or transition through multiple routes.

I attempted to fork this repo to expose the `modalContainer` API on the core Shepherd library... it only changes the rendering of the overlay.. not the modals themselves.

This is a breaking change for me and I may need to consider using the plain Shepherd,js library.. is that the recommended option currently?

**Comment by rwwagner90** [comment]
@grapho I'm not sure I understand. Can you not change the target of the test helpers? You can pass `document.body` as the context for the tests, rather than the default of the Ember testing container.

**Comment by rwwagner90** [comment]
Also, why do you need to fork to expose `modalContainer`? Can't you pass that option currently as part of your steps/tour config?

**Comment by grapho** [comment]
@rwwagner90 Thanks for the response! 

I resolved the issue with the test helpers, so we can close this issue.

However, I did take a look at the tour service in the addon repo... i do not see `modalContainer` being passed to or set onto the tour instance

**Comment by rwwagner90** [comment]
> I resolved the issue with the test helpers, so we can close this issue. I may have posted the issue in a moment of temporary frustration :p

No problem! We have all been there 😃 

> However, I did take a look at the tour service in the addon repo... i do not see modalContainer being passed to or set onto the tour instance, so I just did a quick fork to test that theory.

There is not an explicit option in the service for it, but I think it can be passed as part of your vanilla Shepherd config perhaps? I could be wrong. Let me know what you find!

**Comment by grapho** [comment]
> There is not an explicit option in the service for it, but I think it can be passed as part of your vanilla Shepherd config perhaps? I could be wrong. Let me know what you find!

Confirmed, setting `defaultTourOptions.modalContainer` on the tour service does not do anything on its own.

I could attempt to set the property directly onto Shepherd object.. but as far as I can tell, Shepherd is not instantiated until addSteps is called which is too late (according to the api docs)

**Comment by rwwagner90** [comment]
@grapho You are totally right, we had a lot of updates to make to get this to the current Shepherd API! I just opened a PR to update all that. Mind trying it out?
