### ISSUE TITLE
Why was modalContainer attribute removed since version 4?

### ISSUE THREAD

**Issue by vjgonzalez** [shipshapecode/ember-shepherd#534]
According to [this issue](https://github.com/shipshapecode/ember-shepherd/issues/206) the attribute modalContainer was added to the tour service. In fact it can be seen in [this PR](https://github.com/shipshapecode/ember-shepherd/pull/208). I also see it was released in version 3.3.0. However, it's been removed in version 4 and is currently not available. I can't see any notes on this in the Changelog file. Is there a reason why you removed this? Can it be re-added?

**Comment by rwwagner90** [comment]
@vjgonzalez I'm not sure what you mean. It's still there https://github.com/shipshapecode/ember-shepherd/blob/master/addon/services/tour.js#L423

**Comment by vjgonzalez** [comment]
Yes, it's in the master branch, but not in the releases: check out tag for version 11.0.0:
[](https://github.com/shipshapecode/ember-shepherd/blob/v11.0.0/addon/services/tour.js)

**Comment by rwwagner90** [comment]
Ah sorry, just released a new version. Didn't realize it had not been released.
