### ISSUE TITLE
Ability to pass ember templates to shepherd's text field

### ISSUE THREAD

**Issue by djsegal** [shipshapecode/ember-shepherd#54]
+ It's hard to manually change class names for deeply nested components. (all buttons for example have the `shepherd-button` class.)

+ One way to make it easier would be to have some some style addons (i.e. `ember-shepherd-bootstrap`)

Is there some crucial information I missed in the docs that would make this possible?

----------
#### Update: 9/9/16

Honestly, this issue changed a lot over its 28 day life.

What it became is the realization that due to how [shepherd](https://github.com/HubSpot/shepherd) was designed, we can not currently use htmlbars in a step's text property.

----------

**Comment by djsegal** [comment]
In order to get my setup working, I had to make heavy use of the `text` field on the steps.

How do you pass components and templates to that property?

--------------

Right now, ive been using this kind of setup:

```
    ...
    var introText = document.createElement('div');
    var innerHtml = `<div class="cs-blah">`
    innerHtml += svgJar('logo');
    innerHtml += `</div>...`;
    introText.innerHTML = innerHtml;
    ...
       ...
       options: {
          ...
          text: introText,
          ...
       },
       ...
    ...

**Comment by rwwagner90** [comment]
@djsegal this is a wrapper around the Shepherd library, it does add some extra functionality, but we are limited to what their library can do. Please refer to their docs. It says this:

`text`: The text in the body of the step. It can be one of four types:
* HTML string
* Array of HTML strings
* HTMLElement object
* Function to be executed when the step is built. It must return one the three options above.

So to use a template or component, I believe you would need to do something like integration tests do, and `import hbs from 'htmlbars-inline-precompile';` and use hbs to do hbs strings, which could be a function that returns your template. You could also use ES6 template strings.

I would also be open to a PR to support something behind the scenes, but we still have to pass one of those 4 things to Shepherd itself.

**Comment by djsegal** [comment]
I think an `import hbs from 'htmlbars-inline-precompile';` approach to get it into a `HTMLElement object` state would be the best approach 

i'll try to look into it more

**Comment by rwwagner90** [comment]
@djsegal would you want to take a stab at implementing something and submit a PR or do you think we should just document how you might do it externally and just support passing the things Shepherd supports out of the box?

**Comment by djsegal** [comment]
I think documentation first. And then let the PR come naturally? 

This feels like a feature that someone else will want eventually

**Comment by rwwagner90** [comment]
@djsegal were you able to get the `import hbs from 'htmlbars-inline-precompile';` stuff to work?

**Comment by djsegal** [comment]
At the moment, I'm doing the html compilation inside a route js file.

I was going to refactor it out later using the hbs compiler

**Comment by rwwagner90** [comment]
@djsegal once you get it working, can you submit a PR for how to use hbs to the README?

**Comment by djsegal** [comment]
@rwwagner90:
 + The problem with hbs is that it gives you an object that needs rendering. As [this stackoverflow post](http://stackoverflow.com/a/25041239/5187080) explains, this is actually pretty hard to do in isolation.

 + [One solution on stackoverflow](http://stackoverflow.com/a/35625858/5187080) was to make a utility function that wrapped the template in a component.

--------

I couldn't get this working, though.  😓

**Comment by rwwagner90** [comment]
@djsegal yeah, it would have to work like it does in integration tests.

```js
this.render(hbs`{{x-text mouseInsideComponent=mouseInsideComponent validator=validator value=value}}`);
```

**Comment by rwwagner90** [comment]
@djsegal I subsequently tried to get the hbs inline precompile stuff to work in another project and it just doesn't seem possible, so I think you are stuck creating html with JS or using ES2015 template strings or something. The only way we could truly support Ember components would be to rewrite Shepherd in Ember and that goes beyond the scope of this addon. Is there anything you would like to add to the README about this or should we just close the issue?

**Comment by djsegal** [comment]
I don't know the best course to take.

+ For my case, now I just have a mixin to store a lot of the custom html text (it's ugly, but at least it's in its own file)
+ I think a quick note in the readme describing the limitation might be the best way to go. Maybe it will lead to someone picking up the challenge in the future (either in this addon or a new one)?

**Comment by rwwagner90** [comment]
@djsegal would you want to drop a quick note in the README?

**Comment by rwwagner90** [comment]
@djsegal ^

**Comment by rwwagner90** [comment]
@djsegal sounds great to me. Do you want the easy PR or do you want me to just update it?
