### ISSUE TITLE
No support for advanceOn (shepherd step option)

### ISSUE THREAD

**Issue by djsegal** [shipshapecode/ember-shepherd#55]
From the [step options in the shepherd docs](http://github.hubspot.com/shepherd/index#step-options):

> advanceOn: An action on the page which should advance shepherd to the next step. It can be of the form "selector event", or an object with those properties. For example: ".some-element click", or {selector: '.some-element', event: 'click'}. It doesn't have to be an event inside the tour, it can be any event fired on any element on the page. You can also always manually advance the Tour by calling myTour.next().

**Comment by djsegal** [comment]
The reason there is no support is because there is no reason for it.

+ The problem I was running into is I had a div with a class of `btn`. 
+ `btn` on hover gives a z-index of 2

--------

in my case, to fix this, i used to following css:

```
.shepherd-target.highlight {
  pointer-events: initial !important;
  z-index: 10001 !important;
}
```

**Comment by rwwagner90** [comment]
@djsegal could you elaborate on your issue here? As for advancing on clicking something else on your page, you can just use `this.get('tour').next()` to advance it in your own function or action.

**Comment by djsegal** [comment]
I anchorTo'd an anchor tag with the class `btn`. Because bootstrap add `z-index=2` to `btn` on `:hover`, the button was unclickable. 

------

Adding that css allowed the button to be clicked

**Comment by rwwagner90** [comment]
@djsegal that does not sound like a bug here at all. It sounds like bootstrap changed the css.

**Comment by djsegal** [comment]
Yup. Closing the issue.
