### ISSUE TITLE
Body classes on tour complete

### ISSUE THREAD

**Issue by sicdigital** [shipshapecode/ember-shepherd#59]
I have a few styles that I'm adding to my app based on wether the tour is actually running. This is working great except that all of the classes for the tour persist even when the tour has been completed or cancelled. It would be really nice if the tour was torn down once it was finished.

**Comment by sicdigital** [comment]
It looks like I have some other issue. I'm seeing that I have `shepherd-enabled` and `shepherd-active` available to me, but they are working inconsistently in my app.

**Comment by rwwagner90** [comment]
@sicdigital this is the way Shepherd works out of the box, it does not tear down when you complete the tour, I think because then if you wanted to start it again, no setup is required.

**Comment by rwwagner90** [comment]
Do you need to completely remove all the Shepherd classes and elements or do you just need a way to tell if the tour is active or not? Please elaborate on your use case and we can try to find a solution.

**Comment by sicdigital** [comment]
Hey @rwwagner90, I actually ended up using the `shepherd-active` class, so the add-on already supported what I needed to do. I think you're ok to close the issue. Thanks for the quick response, everything is working great :)

**Comment by rwwagner90** [comment]
@sicdigital awesome! If you feel like the README could use some updates on documenting how to do the things you were trying to do, please feel free to submit a PR 😄
