### ISSUE TITLE
Using npm to pull in sheperd and tether dependencies

### ISSUE THREAD

**Issue by ianpetzer** [shipshapecode/ember-shepherd#74]
Hi there,

Thanks for this amazing add-on. We've been trying it out with some great success.

I was just wondering if you've ever thought of pulling the dependencies in via npm instead of bower?

The reason I'm asking is that we also use ember-modal-dialog and ember-tooltips both of which use ember-tether to pull in the tether dependency via npm.

I'm not completely sure what happens if you pull tether in through npm and bower. I was just curious if you'e ever thought of this before?

Thanks,
Ian

**Comment by rwwagner90** [comment]
Hi @ianpetzer.

Glad to hear you're enjoying the addon!

I have gone back and forth on this. I do favor removing the dependency on bower, but I was not aware of ember-cli-node-assets, which it looks like ember-tether is using to accomplish this. I thought ember-browserify was the only viable option.

I can look into making the switch.

**Comment by rwwagner90** [comment]
@ianpetzer I was able to make this addon depend on ember-tether, so *hopefully* that will fix the potential double dependency issue. Version 2.4.0 has the change. Please try it out!

**Comment by ianpetzer** [comment]
Amazing! I will check it out and report back!

**Comment by ianpetzer** [comment]
@rwwagner90 I can confirm that I've upgraded to v2.4.4 and everything is working beautifully without the bower dependency tether-sheperd.

Thanks so much!
